### ISSUE TITLE
Feature Request: GUI Builder

### ISSUE THREAD

**Issue by Immortalin** [yegor256/tacit#10]
A GUI builder a la [this](http://tutsme-webdesign.info/best-bootstrap-visual-editor/)

**Comment by vkeusebio** [comment]
Do we really need such?

**Comment by yegor256** [comment]
@Immortalin I don't think such a feature can be in scope of this project...

**Comment by Immortalin** [comment]
@vkeusebio the title of it did say it is for dummies, or should it be "dummies"? Anyway, @yegor256 it is already quite good in its current state, a GUI builder would be cherry on the icing....
