### ISSUE TITLE
Theming options

### ISSUE THREAD

**Issue by tofran** [yegor256/tacit#102]
I was just introduced to tacit by @filfreire , it looks amazing, thank you for powering my frontend laziness :laughing:
I immediately realized that there's something missing, so I have a feature request:
There should be an easy way to theme tacit.
I would like to change the colors easily, or even better just include the X theme file and it would change automagically.

**Comment by 0crat** [comment]
@filfreire please, pay attention to this issue

**Comment by akshayvinchurkar** [comment]
Ok so this is something like foundation framework they have themes like github bootstrap LinkedIn type sounds cool @tofran

**Comment by yegor256** [comment]
@tofran I like the idea! We can just create different CSS files: `tacit-css-1.0`, `tacit-css-steel-1.0`, `tacit-css-bright-1.0`, etc. You either pick the default one of the one with a different theme. /cc @filfreire

**Comment by yegor256** [comment]
@tofran or maybe it's better to create new CSS files, which users will link right after the main `tacit-css.css`. I guess, this will be a better approach. The main CSS will define all styles correctly and the theme CSS will alter them to make them look a bit different.

**Comment by akshayvinchurkar** [comment]
@yegor256 so let's make it

**Comment by yegor256** [comment]
@tofran @akshayvinchurkar let's start with the first theme. Let's make it, say, dark :) Do you want me to create the first one, to show an example?

**Comment by akshayvinchurkar** [comment]
@yegor256 if you create one then we can better understand what you want to customise or what not

**Comment by tofran** [comment]
@yegor256 @akshayvinchurkar yes that would be great.

**Comment by filfreire** [comment]
@tofran closing this issue in favour of #163 
Feel free to contribute with new issues and pull requests 👍 

/cc @yegor256

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#102` is not assigned, can't get performer
