### ISSUE TITLE
can we create Example pages.

### ISSUE THREAD

**Issue by akshayvinchurkar1** [yegor256/tacit#104]
can we create Example pages like foundation did in their framework [foundation](https://foundation.zurb.com/templates.html) 
I mean ordinary pages that every website or web-app required like login and registration page or homepage for app or landing page simple not too complicated in that way users of tacit will better understand how to use tacit

**Comment by 0crat** [comment]
@filfreire please, pay attention to this issue

**Comment by filfreire** [comment]
@akshayvinchurkar1 the idea seems nice.
Could you kindly make a small list of example pages you think would be fit to create?

Then afterwards we can decide with @yegor256 which ones make the most sense and create an issue for each one that anyone can contribute.

**Comment by tofran** [comment]
I also agree, but since tacit is simple, we should keep the examples simple too.
I would recommend the following: 

- A simple project page
- Blog page
- Form, like the one in `index.html`
- "About me" page
- Login screen

**Comment by yegor256** [comment]
@akshayvinchurkar1 I don't think we need anything aside from the `index.html` we already have. If we need more HTML examples there, let's just add them right there, to that page.

**Comment by akshayvinchurkar1** [comment]
examples makes life simple as far as i know just add CSS html code and done everyone want free code and style does that make sense @yegor256 @tofran @filfreire

**Comment by filfreire** [comment]
Closing this issue, following @yegor256 's comment https://github.com/yegor256/tacit/issues/104#issuecomment-341096097

Let's follow this approach: we can setup each example on it's separate repository, and add a link to that repository on tacit's README, maybe on an examples section.

For instance, something like https://github.com/filfreire/demo-tacit could then be added under the [Usecases section on the README](https://github.com/yegor256/tacit/#usecases-of-tacit-framework).

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#104` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
