### ISSUE TITLE
Add git commit guideline to CONTRIBUTING.md

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#109]
Edit CONTRIBUTING.md to mention the following:
* Every commit/PR should preferably be linked to a Github issue; If it's not, it's recommended to create an Issue first and then commit and open a PR;
* Commit message should follow a given pattern, or at least always mention the `#<issue-number>`

**Comment by filfreire** [comment]
PR #131 was merged. Closing this issue.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#109`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#109` is not in scope.
