### ISSUE TITLE
Mobile styles / responsiveness

### ISSUE THREAD

**Issue by jehna** [yegor256/tacit#11]
Now the sample page breaks down in mobile widths (even though there's `<meta name="viewport" content="width=device-width, initial-scale=1.0"/>` tag which indicates that this CSS framework probably should, in the perfect world, be "mobile opitimized").

@yegor256 is this the direction you'd like the framework to be developed to? I can start working on the responsiveness if you think the ideology matches with this project.

### 1. Form element widths
Some of the form elements overflow from main container:
![screen shot 2015-04-10 at 10 36 49](https://cloud.githubusercontent.com/assets/2676795/7083705/9a172bae-df6d-11e4-989c-0c58e290925d.png)

P.S. `input[name='consent']` is missing `id='consent'`, so tapping the label does not select the input properly

### 2. Margins in mobile sizes
The margins are way too big in mobile sizes (escalating in 320px iphone width).

Compare this screenshot from the example page:
![screen shot 2015-04-10 at 10 48 16](https://cloud.githubusercontent.com/assets/2676795/7083851/6758ece6-df6f-11e4-9f65-e12164101901.png)

With a similar screenshot from popular Bootstrap framework:
![screen shot 2015-04-10 at 10 48 42](https://cloud.githubusercontent.com/assets/2676795/7083867/7c637854-df6f-11e4-96a1-8f22b54f0f6a.png)

You see that the amount of pixels in screen for the actual content is much bigger in the Bootstrap's version. I'd remove the grey area completely when in mobile sizes.

### 3. Table responsiveness
This is more complicated issue, but I'd like to point out that the example table actually would just fit to 320px width if the margins were smaller (see 2.)
![screen shot 2015-04-10 at 10 43 23](https://cloud.githubusercontent.com/assets/2676795/7083820/06f238da-df6f-11e4-847c-8e75db1f4203.png)

**Comment by yegor256** [comment]
@jehna thanks for your comments. of course, I'd like to make keep it all responsive. please, submit pull requests. but let's do one problem per pull request. the smaller the pull request the better. it will be easier for me to manage them. thanks!

**Comment by jehna** [comment]
@yegor256 would it make sense if you'd create a branch called `responsive` so I could do pull requests to that branch for each feature?

**Comment by yegor256** [comment]
@jehna just send them to the `master`, why not?

**Comment by jehna** [comment]
@yegor256 to have them contained before everything's ready. But I can send them to master if that's fine to you :)

**Comment by yegor256** [comment]
@jehna sure, that's fine, let's do them one by one. just make sure each one of them is not breaking anything... I'm actually planning to add some sort of layout testing, like it's done in bootstrap. that will help in the future. but for now let's just try to be attentive

**Comment by yegor256** [comment]
@jehna I think we can close this one, as all problems mentioned above are fixed (or reported in separate tickets), right?

**Comment by jehna** [comment]
@yegor256 yes, a leas the sample page is now good and responsive. If any further issues occur later, we can make separate tickets. Closing this ticket now.
