### ISSUE TITLE
sup and sub

### ISSUE THREAD

**Issue by yegor256** [yegor256/tacit#110]
To my knowledge, we don't have any formatting for `<sup>` and `<sub>` elements. Let's fix it please. See https://gist.github.com/unruthless/413930 I believe it should go to `_typography.scss`

**Comment by 0crat** [comment]
@filfreire please, pay attention to this issue

**Comment by akshayvinchurkar1** [comment]
#111  i create the pull request as per your suggestion

**Comment by filfreire** [comment]
@akshayvinchurkar1 kindly follow-up on the comments that I posted for PR #111.

**Comment by filfreire** [comment]
@akshayvinchurkar1 kindly follow-up on the comments posted on https://github.com/yegor256/tacit/pull/112

**Comment by akshayvinchurkar1** [comment]
#118  will fixed the issue. i just want to ask a question about git if i want to include only commits i choose for pull request how can i do that?

**Comment by filfreire** [comment]
@yegor256 kindly close this issue, it's implemented and released under https://github.com/yegor256/tacit/releases/tag/1.2.0 👍

**Comment by yegor256** [comment]
@akshayvinchurkar1 @filfreire thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#110`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#110` is not in scope.
