### ISSUE TITLE
Add section: Built with Tacit

### ISSUE THREAD

**Issue by 0x13a** [yegor256/tacit#113]
Would be awesome to see who is using TacitCSS and what kind of websites people built with it.
So this translate into having a section where we list *Built with Tacit*

**Comment by 0crat** [comment]
@filfreire please, pay attention to this issue

**Comment by akshayvinchurkar1** [comment]
@0x13a its great idea but how we know people using it as compare to other frameworks tacit has very small footprint

**Comment by 0x13a** [comment]
you can start by putting a google form in the readme for example

**Comment by 0x13a** [comment]
I just used TacitCSS to build my site http://whoismining.com/

**Comment by akshayvinchurkar1** [comment]
@0x13a thats great what type of fields you want to expect in a google form?

**Comment by akshayvinchurkar1** [comment]
so we can implement

**Comment by 0x13a** [comment]
website url should be enough. We could also ask if it's used for a side project or in production by a company, but I'd say the url is enough

**Comment by filfreire** [comment]
@0x13a I like the idea.
We could close this issue by doing a PR creating this section and list on README, or maybe edit the index page with the same section and list.

@0x13a @akshayvinchurkar1 would you be willing to open a PR with this change?

BTW, After finishing a PR for this we could close this issue and open a separate new issue just to handle the google form part of submitting "my site is built with Tacit". For that part I think it's best that @yegor256 handle/oversees work directly.

**Comment by 0x13a** [comment]
ok great

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#113`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#113` is not in scope.
