### ISSUE TITLE
Color Contrast

### ISSUE THREAD

**Issue by jraller** [yegor256/tacit#114]
The color contrast for the following elements do not pass the accessibility tests run by [lighthouse](https://developers.google.com/web/tools/lighthouse/):
```
<a>
<button>
<code>
<figcaption>
<footer>
<h6>
<kbd>
```
New colors can be checked with: https://webaim.org/resources/contrastchecker/ or other tools.

**Comment by 0crat** [comment]
@filfreire please, pay attention to this issue

**Comment by filfreire** [comment]
@jraller thank you 👍 
Feel free to submit a PR to fix this issue.

**Comment by jraller** [comment]
Pull request #116 submitted.

**Comment by filfreire** [comment]
@jraller PR #116  was merged. Could you kindly close this issue?

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#114`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#114` is not in scope.
