### ISSUE TITLE
Issue loading images on icon and top of index.html

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#128]
**(bug)**
There seems to be an issue loading the tacit logo as an icon and on top of index.html page.
When tested locally it seemed to work fine.

Related issues: #124 #125 

This happened after release of v.1.2.1

Affects: https://yegor256.github.io/tacit/

**Image:**
![screen shot 2017-12-07 at 07 56 32](https://user-images.githubusercontent.com/11976836/33704388-344367a6-db24-11e7-880b-4f09ad4dad9f.png)

**Icon:**
![screen shot 2017-12-07 at 07 57 33](https://user-images.githubusercontent.com/11976836/33704432-58c04be4-db24-11e7-9836-14a50e5d7923.png)

**Comment by filfreire** [comment]
@rultor release, tag is `1.2.2`

**Comment by filfreire** [comment]
Images added to rultor release step. Attempted to fix images paths but failed, re-opening a PR with fix of paths and alt field for logo image on index.html.

**Comment by filfreire** [comment]
Done, seems OK now. @yegor256 FYI

<img width="673" alt="screen shot 2017-12-07 at 16 45 50" src="https://user-images.githubusercontent.com/11976836/33726845-23be6b2a-db6e-11e7-8d68-3eaf74d1897b.png">

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#128` is not in scope.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#128`.
