### ISSUE TITLE
IE9 checkbox is ugly

### ISSUE THREAD

**Issue by jehna** [yegor256/tacit#13]
The test page's checkbox is small and is not centered on IE9:
![screen shot 2015-04-10 at 19 23 18](https://cloud.githubusercontent.com/assets/2676795/7092040/4754155e-dfb7-11e4-9138-84c9879947be.png)

**Comment by yegor256** [comment]
@jehna do you know how to fix this?

**Comment by jehna** [comment]
@yegor256 no out-of-the-box idea

**Comment by Kyokou** [comment]
Remove input[type='checkbox'] { margin-top: 8.1px; } 

Doesn't seem to break things in Chrome. Fixes IE. Didn't check Firefox, but you can also use a @-moz-document declaration for Firefox if it breaks in Firefox.

**Comment by yegor256** [comment]
@filfreire where we are with his?

**Comment by filfreire** [comment]
@yegor256 

Currently on IE9
![ie9](https://user-images.githubusercontent.com/11976836/37558306-d50421c4-2a09-11e8-8c53-a84eb09c69ec.png)

The centering issue is fixed currently on Tacit `1.2.8`. 
But, the size doesn't seem so. I've been searching and I believe we can try and workaround size with css scale:
```
 -ms-transform: scale(2); /* IE */
```
[Source](https://stackoverflow.com/a/10415275/7468990)

In comparison to other IE browsers:
On IE11 (latest IE aside from Edge)
![ie11_win10](https://user-images.githubusercontent.com/11976836/37558310-d8faec9a-2a09-11e8-855a-a78c54b4675c.png)

On Edge 41
![edge41_win10](https://user-images.githubusercontent.com/11976836/37558311-e116b88c-2a09-11e8-9d62-3fbc68945d76.png)

**Comment by filfreire** [comment]
@jehna closing this issue since it's half resolved. Created issue #183 to follow-up on fixing the size of the checkbox.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#13` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
