### ISSUE TITLE
A small mistake with href in README

### ISSUE THREAD

**Issue by alex-semenyuk** [yegor256/tacit#143]
Instead of

`<link rel="stylesheet" href="//cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-VERSION.min.css"/>`

should be 

`<link rel="stylesheet" href="https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-VERSION.min.css"/>`

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this issue

**Comment by filfreire** [comment]
@alex-semenyuk code is merged, you can close the issue.
