### ISSUE TITLE
CONTRIBUTING.md link is broken in README

### ISSUE THREAD

**Issue by alex-semenyuk** [yegor256/tacit#145]
https://github.com/yegor256/tacit/blob/master/CONTRIBUTING.md doesn't exist. Need to remove link or add  proper CONTRIBUTING.md

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this issue

**Comment by filfreire** [comment]
@alex-semenyuk thanks for opening this issue. The file was removed in commit https://github.com/yegor256/tacit/commit/36853a2ed25051aea942b35f25e15f826976b9c5 made by @yegor256.

I opened PR #146 to tackle this.

/cc @yegor256

**Comment by filfreire** [comment]
@alex-semenyuk PR #146 was merged, you can close this issue.
