### ISSUE TITLE
Tacit logo appears streched for Android 4.0 default browser

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#148]
How to reproduce:
On Android 4.0 default browser, visit yegor256.github.io/tacit/

Screenshot:
![android_4_browser_480_800_002](https://user-images.githubusercontent.com/11976836/37564288-c0d179d2-2a8a-11e8-8c89-4473c11a6f61.png)

**Comment by filfreire** [comment]
@yegor256 please label this issue as bug.

**Comment by 0crat** [comment]
Job [#148](https://github.com/yegor256/tacit/issues/148) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @filfreire[/z](https://www.0crat.com/u/filfreire)

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by filfreire** [comment]
@rultor release `1.2.9`

**Comment by filfreire** [comment]
@rultor release, tag is `1.2.9`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da044789-3a52-46a3-9276-7cb0d37b26bd, thread: BkParallel-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C7BNDNSNR" in 1min: 333a07cbbe87/4hr/0/0/false/false by QuartzScheduler_Worker-4
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da044789-3a52-46a3-9276-7cb0d37b26bd, thread: BkParallel-9
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C7BNDNSNR" in 1min: 333a07cbbe87/5hr/0/0/false/false by QuartzScheduler_Worker-4
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da044789-3a52-46a3-9276-7cb0d37b26bd, thread: BkParallel-6
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C7BNDNSNR" in 1min: 333a07cbbe87/6hr/0/0/false/false by QuartzScheduler_Worker-4
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da044789-3a52-46a3-9276-7cb0d37b26bd, thread: BkParallel-7
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C7BNDNSNR" in 1min: 333a07cbbe87/7hr/0/0/false/false by QuartzScheduler_Worker-4
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da044789-3a52-46a3-9276-7cb0d37b26bd, thread: BkParallel-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C7BNDNSNR" in 1min: 333a07cbbe87/8hr/0/0/false/false by QuartzScheduler_Worker-4
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da044789-3a52-46a3-9276-7cb0d37b26bd, thread: BkParallel-2
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C7BNDNSNR" in 1min: 333a07cbbe87/9hr/0/0/false/false by QuartzScheduler_Worker-4
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da044789-3a52-46a3-9276-7cb0d37b26bd, thread: BkParallel-4
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C7BNDNSNR" in 1min: 333a07cbbe87/10hr/0/0/false/false by QuartzScheduler_Worker-4
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da044789-3a52-46a3-9276-7cb0d37b26bd, thread: BkParallel-8
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C7BNDNSNR" in 1min: 333a07cbbe87/11hr/0/0/false/false by QuartzScheduler_Worker-4
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job [#148](https://github.com/yegor256/tacit/issues/148) is now out of scope
