### ISSUE TITLE
Is there support for making drop down menus?  Or how do I do it?

### ISSUE THREAD

**Issue by ms4720** [yegor256/tacit#153]
Hello,

I love the idea of this project, just write html and it looks good.  Is there a way to do drop down menus?  they are a really basic UI element that I need and there are no examples I can find.

Thanks

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this issue

**Comment by 0crat** [comment]
@ms4720[/z](https://www.0crat.com/u/ms4720) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7BNDNSNR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by akshayvinchurkar** [comment]
@ms4720 hey tacit provide just style for the core tags of html. drop-down is not a tag you can use select tag instead

**Comment by ms4720** [comment]
I am a very ignorant person on the front end, how would I use select for navigation menus?  Ie pick this option and go to that page?

**Comment by akshayvinchurkar** [comment]
ok then use bootstrap or foundation for that because tacit cant help you in this case

**Comment by ms4720** [comment]
Thanks

**Comment by filfreire** [comment]
Hi @ms4720, with tacit you can do a navigation menu similar to what you'd find for example in [my homepage](http://filfreire.com) or other pages that use tacit:

Screenshot:
<img width="476" alt="screen shot 2018-05-02 at 08 40 54" src="https://user-images.githubusercontent.com/11976836/39511256-b6306182-4de4-11e8-8faa-ac16cb5dc6a1.png">


Code:
```
<nav>
    <ul>
      <li><a href="/">home</a></li>
      <li><a href="/about">about</a></li>
      <li><a href="/projects">projects</a></li>
      <li><a href="/talks">talks</a></li>
      <li><a href="/other-stuff">other stuff</a></li>
    </ul>
  </nav>
```

**Comment by akshayvinchurkar** [comment]
@filfreire he want dropdown menu

**Comment by ms4720** [comment]
@filfreire that could work, click on nav and put the submenus underneath in another bar.  @akshayvinchurkar sorry for not having a good question, I really am pretty clueless here.

**Comment by akshayvinchurkar** [comment]
@filfreire now i am also clueless here tacit has dropdowns?

**Comment by ms4720** [comment]
@akshayvinchurkar perhaps it can fake it. I will play and see. That basic nav tag bit of code would be nice in the demo page

**Comment by ms4720** [comment]
@akshayvinchurkar I understand the goal of tactic is to make html look good by default, I really like that goal.  The thing is you lose a lot of functionality that way and it would be nice to see workarounds for them, this is very useful to people like me who do not know frontend dev well if at all. Ie you can't have drop-down menus but you can nest nav tags and that might be good enough(even if it is a bit of a hack). This is a little beyond the current scope for docs but it will make things much better for ignorant people like me trying to get something done.

**Comment by akshayvinchurkar** [comment]
@yegor256  hey big brother take a look at this. can we implement that? i mean dropdown menus in tacit @ms4720 if he is ok with it we can take this as improvement.

**Comment by ms4720** [comment]
not drop down but this:
<nav>
    <ul>
      <li><a href="/">home</a></li>
      <li><a href="/about">about</a></li>
      <li><a href="/projects">projects</a></li>
      <li><a href="/talks">talks</a></li>
      <li><a href="/other-stuff">other stuff</a></li>
    </ul>
  </nav>

Where there is another nav section under it, I go to the talks page there is a specific talks nav bar under the main nav menu.  Not drop down but it keeps me from learning JS and BS and Node and lord knows what else just to have things look ok

**Comment by yegor256** [comment]
@filfreire @ms4720 @akshayvinchurkar I think that drop-downs (and any other non-HTML5 elements) are out of scope. We are HTML5 strictly compliant. If HTML5 doesn't have it, we don't have it as well. If you need, there are many other libraries that you can use.

**Comment by ms4720** [comment]
@yegor256 I agree, I also think that much of the target audience is like me clueless about front-end development.  What I really need is some kind of menu system, could be a hack like nested/stacked nav sections ( I did not know the nav tag existed ).  If the demo was expanded with examples like "Fake menu system" people could see that and see workarounds that they could use.

**Comment by akshayvinchurkar** [comment]
@ms4720 in this case try this its not build with tacit but it helps

https://codepen.io/andornagy/pen/xhiJH

**Comment by ms4720** [comment]
@akshayvinchurkar  thanks looks nice

**Comment by filfreire** [comment]
Hey @ms4720 I created issue https://github.com/yegor256/tacit/issues/162 to (in a way) follow-up on this issue. For actual dropdown menus there are many other libraries that you can use. Let me know if you'd feel it's important to add this info as a note on the README. Otherwise I'm closing the issue, ok? 👍

**Comment by ms4720** [comment]
I think a hacks section is a good thing here, stacked nav tags is a hack that I could live with.  Ie you can't have nested menus, but this looks close and is doable could be handy.   A short list of options that play well with tacit could also be handy for newcomers like me, if you really need a menu system these play nice with tacit.  With that said feel free to close the issue.

**Comment by filfreire** [comment]
@ms4720 thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@25fbab20-c312-42db-aced-b573bac3c501, thread: pool-401-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-03T12:29:24.119Z"
```

[0.28.14](https://github.com/zerocracy/farm): Issue: yegor256/tacit#153, Action: `closed`
