### ISSUE TITLE
Generate a new token for npmjs.com, to upload tacit-css during rultor release task

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#157]
Currently when releasing where getting this notice:

```
\u001b[K\u001b[?25hnpm WARN notice Due to a recent security incident, all user tokens have been invalidated. Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details. To generate a new token, visit https://www.npmjs.com/settings/~/tokens or run "npm login".
\u001b[?25l[..................] - publish:tacit-css@1.3.1: WARN notice Due to a recent sec\u001b[K
```
And the release of a new tag fails (example with latest attempt, tag `1.3.1`,  [here](https://github.com/yegor256/tacit/pull/156#issuecomment-405914400))

@yegor256 let's fix this, generating a new token and documenting the fix somewhere in the readme for any other times this may happen again.

**Comment by filfreire** [comment]
@yegor256 can you document somewhere how you did the fix so we can close this issue?

**Comment by yegor256** [comment]
@filfreire well, the token is kept in my private file, which is taken by Rultor during deployment. Do we need to document that? It's already obvious in `.rultor.yml`: https://github.com/yegor256/tacit/blob/master/.rultor.yml#L3

**Comment by filfreire** [comment]
@yegor256 I think it should be apparent somewhere for the future, but for now it's ok. Closing this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#157` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
