### ISSUE TITLE
Theming options are now external

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#163]
Goal: Create a distinction between "built with tacit" and "examples"

In an effort to keep Tacit small let's avoid tickets for different skins, that would make tacit more complex and less unique.
Let's keep it super simple and always with the same look-and-feel.
On the other hand, if you want something more custom — make it on top of Tacit, like for example:
https://github.com/Kimeiga/kacit

closes #102

**Comment by filfreire** [comment]
@yegor256 PR is merged, closing this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#163` is not assigned, can't get performer
