### ISSUE TITLE
Warning during npm install: license should be a valid SPDX license expression

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#176]
We have a warning being triggered on `npm install` command:

```
npm WARN tacit-css@0.0.0 license should be a valid SPDX license expression
```

This was seen happening on a Mac OSX 64 bit, node version `v10.9.0`.

**Comment by filfreire** [comment]
fixed in @alex-semenyuk commit, closing this issue
@alex-semenyuk thanks 👍

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#176` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
