### ISSUE TITLE
Old Android stock browser overflows <fieldset> tag

### ISSUE THREAD

**Issue by jehna** [yegor256/tacit#18]
The Android's old (pre-Chrome) stock browser does not restrict the `<fieldset>` tag to it's parent's boundaries:
![screenshot_2015-04-10-23-15-09](https://cloud.githubusercontent.com/assets/2676795/7096351/0c0fa294-dfd8-11e4-8b93-ab1a57b60322.png)

For discussion see [the StackOverflow thread discussing this bug in various browsers](http://stackoverflow.com/questions/17408815/fieldset-resizes-wrong-appears-to-have-unremovable-min-width-min-content/17863685#17863685):

> Unfortunately, in Android 4.1.2 Stock Browser and possibly other similarly old versions, this has no effect.

**Comment by yegor256** [comment]
@jehna thanks! any ideas how to fix this?

**Comment by jehna** [comment]
@yegor256 googling showed no relevant results. But the worst part is that you cannot inspect/debug the Android stock browser (like you can e.g. Chrome). So finding a solution to this would be quite a brute-force task.

Ofc there are better googlers than myself :D

**Comment by yegor256** [comment]
@filfreire where we are with his?

**Comment by filfreire** [comment]
@yegor256 I'll retest with different versions of older Android browser and update on current status.

**Comment by filfreire** [comment]
@yegor256 I think we can close this issue. See below:

Android 2.3.3 default browser (this Android version is deprecated by Google)
![android_233_480_800_001](https://user-images.githubusercontent.com/11976836/37559089-ac098a4e-2a17-11e8-91fc-d9dbd29a2c43.png)


Android 4.0 default browser (this Android version is latest "suported" by Google)
![android_4_browser_480_800_001](https://user-images.githubusercontent.com/11976836/37559084-86660ace-2a17-11e8-882f-963bce1457e8.png)

(Screenshots from AVD Android emulators (as close to physical as possible))

**Comment by yegor256** [comment]
@filfreire thanks, closing!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
