### ISSUE TITLE
Define better style for "big tables" for non-mobile screens (desktop/laptop)

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#182]
Following #89 , let's define a proper style for when the screen is not necessarily small, but the table overflows the main `<section>` element (like on 0crat's board page)

<img width="1451" alt="screen shot 2019-01-29 at 23 59 40" src="https://user-images.githubusercontent.com/11976836/51946491-fbe32980-2421-11e9-8869-33312b75440e.png">

/cc @teriyakigod2

**Comment by 0crat** [comment]
Job [#182](https://github.com/yegor256/tacit/issues/182) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#182](https://github.com/yegor256/tacit/issues/182); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#182](https://github.com/yegor256/tacit/issues/182) assigned to @filfreire[/z](https://www.0crat.com/u/filfreire), here is [why](https://www.0crat.com/footprint/C7BNDNSNR/3ad945ef-4fa2-4c7f-8658-cd4a7d3bedb3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @filfreire[/z](https://www.0crat.com/u/filfreire)

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by filfreire** [comment]
Closing this issue, implemented in PR #189

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#182](https://github.com/yegor256/tacit/issues/182); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#182](https://github.com/yegor256/tacit/issues/182) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @filfreire[/z](https://www.0crat.com/u/filfreire)
