### ISSUE TITLE
TABLEs are not responsive

### ISSUE THREAD

**Issue by yegor256** [yegor256/tacit#188]
Try to create a table with many columns and see how it behaves when the width of the screen is small. I believe, it should convert itself to a non-TABLE mode.

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this issue

**Comment by filfreire** [comment]
@yegor256, thanks, I'll look into this.

**Comment by yegor256** [comment]
@filfreire see how it's done here https://github.com/zold-io/zold.github.io/blob/master/sass/health.scss
and works here: http://www.zold.io/health.html

**Comment by filfreire** [comment]
@rultor release, tag is `1.4.1`

**Comment by filfreire** [comment]
@yegor256 finished and released an improvement with PR #189 , also contributed a fix on https://github.com/zerocracy/farm/pull/1914 .

I'm marking this issue as closed. Feel free to re-open (or open a new one) in case there's need for improvements.

**Comment by 0crat** [comment]
Job [#188](https://github.com/yegor256/tacit/issues/188) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#188](https://github.com/yegor256/tacit/issues/188) assigned to @filfreire[/z](https://www.0crat.com/u/filfreire), here is [why](https://www.0crat.com/footprint/C7BNDNSNR/827ae760-a984-4762-9a8c-690cc5a0f219); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#188](https://github.com/yegor256/tacit/issues/188) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @filfreire[/z](https://www.0crat.com/u/filfreire)

**Comment by merobero** [comment]
https://github.com/yegor256/elegantobjects.github.io/issues/3#issuecomment-470848926
