### ISSUE TITLE
Default font-size in tables is too small

### ISSUE THREAD

**Issue by wholegroup** [yegor256/tacit#192]
After PR #189 was merged the table default font-size became too small. Why is it 65%, not i.e. 80%?
![image](https://user-images.githubusercontent.com/553191/53647638-696bbb00-3c57-11e9-90ac-d5b6c4096a08.png)

As I understand this size was chosen because of https://github.com/zerocracy/farm/issues/1778, but it's bad approach since Tacit is public project and IMHO it doesn't look well. And It still doesn't fix issues with wide tables.

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this issue

**Comment by 0crat** [comment]
@wholegroup[/z](https://www.0crat.com/u/wholegroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7BNDNSNR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by filfreire** [comment]
@wholegroup you're right, it's not the best solution. 
I'll try to figure out a way to properly fix it. Meanwhile if you see a good way to fix it, kindly contribute with a pull-request.

**Comment by 0crat** [comment]
Job [#192](https://github.com/yegor256/tacit/issues/192) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @wholegroup[/z](https://www.0crat.com/u/wholegroup)

**Comment by filfreire** [comment]
@wholegroup with the latest release, `1.4.2`, font sizes should be back to normal.

**Comment by 0crat** [comment]
The job [#192](https://github.com/yegor256/tacit/issues/192) assigned to @filfreire[/z](https://www.0crat.com/u/filfreire), here is [why](https://www.0crat.com/footprint/C7BNDNSNR/ca2244f1-d7bd-4b9b-87d4-c11cc85df82c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@wholegroup I believe it's fixed

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) resigned from [#192](https://github.com/yegor256/tacit/issues/192), since the job is not in scope anymore
