### ISSUE TITLE
Style autofix tool

### ISSUE THREAD

**Issue by dz-s** [yegor256/tacit#197]
To avoid warnings by people who knows nothing about alphabet, I suggest to write grunt-task/small tool wrapped with task, that will sort out all properties in css in alphabetical order.

moreover, we can add indentation check and fix etc.

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this issue

**Comment by 0crat** [comment]
@dz-s[/z](https://www.0crat.com/u/dz-s) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7BNDNSNR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by filfreire** [comment]
@dz-s seems like a nice idea, let's do it.
Basically you're sugesting to add a task for the developer to optionaly fix the lint error when css properties are not, for example, in alphabetical order, correct?

**Comment by dz-s** [comment]
@filfreire yep

**Comment by yegor256** [comment]
@filfreire how is this related to Tacit?

**Comment by yegor256** [comment]
@filfreire I'd suggest to close this. It's not related to Tacit anyhow.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#197` is not assigned, can't get performer
