### ISSUE TITLE
Input borders not shown when used with Elm

### ISSUE THREAD

**Issue by vbrandl** [yegor256/tacit#204]
Hey Yegor,

I started another service and decided to use Tacit again. I'm using the latest minified version of Tacit.

I have a mostly static HTML page with some JavaScript (generated with Elm) thrown in: https://github.com/vbrandl/yagcdn/blob/master/frontend/template.html

The JavaScript part is only responsible for generating an `input` field, parse the input and update another field if the input matches a pattern.

When I create the `input` fields without any styling at all, the border is missing, so I had to style the border explicitly (e.g. [here](https://github.com/vbrandl/yagcdn/blob/master/frontend/template.html#L22) or [here](https://github.com/vbrandl/yagcdn/blob/master/frontend/src/Main.elm#L65))

I don't know if this is an Elm issue or a Tacit issue but every other style gets applied, so I guess it belongs here.

Also if you'd like another (kinda interactive) example of Tacit in production, you can add https://yagcdn.tk/ to the list of usecases ;)

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this issue

**Comment by 0crat** [comment]
@vbrandl[/z](https://www.0crat.com/u/vbrandl) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7BNDNSNR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@vbrandl you should use:

```
<input type="text">
```

Without `type` there is no border.

**Comment by vbrandl** [comment]
Thank you.

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#204` is not assigned, can't get performer
