### ISSUE TITLE
Missing 'Disabled' Button

### ISSUE THREAD

**Issue by Kyokou** [yegor256/tacit#21]
I suggest having the Reset button be disabled to show styles of a disabled button. 

Reasoning: 
http://www.nngroup.com/articles/reset-and-cancel-buttons/
15 years later this is still true.

**Comment by yegor256** [comment]
@Kyokou makes sense... thanks

**Comment by vkeusebio** [comment]
@Kyokou I'll work on it.

**Comment by yegor256** [comment]
@rultor release, tag is `0.5`

**Comment by yegor256** [comment]
@Kyokou the problem seems to be fixed, please check and close the ticket
