### ISSUE TITLE
fiedset rendering is broken in latest Chrome

### ISSUE THREAD

**Issue by yegor256** [yegor256/tacit#211]
Open this page: https://yegor256.github.io/tacit/

The `fieldset` part is not rendering elements vertically.

**Comment by yegor256** [comment]
@filfreire let's release please?

**Comment by filfreire** [comment]
@rultor release, tag is `1.5.2`

**Comment by filfreire** [comment]
@yegor256 done. Seems OK in Firefox, but still broken in Chrome and Chromium-based Edge. Example:

![tacit](https://user-images.githubusercontent.com/11976836/101286308-045cd600-37ea-11eb-8d50-43c00dacc63c.jpg)

**Comment by filfreire** [comment]
@rultor release, tag is `1.5.3`

**Comment by filfreire** [comment]
@yegor256 you should see it fixed now on https://yegor256.github.io/tacit/ after release [1.5.3](https://github.com/yegor256/tacit/releases/tag/1.5.3)

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#211` is not assigned, can't get performer
