### ISSUE TITLE
Buttons' background is too dark

### ISSUE THREAD

**Issue by albatros2ko** [yegor256/tacit#22]
Isn't the background color for normal buttons too dark? They look like disabled rather than clickable at first look until you hover your mouse over it.

**Comment by yegor256** [comment]
@vkeusebio I merged the pull request. this issue seems to be fixed, right?

**Comment by yegor256** [comment]
@filfreire where we are with his?

**Comment by yegor256** [comment]
@filfreire could you please check other tickets too? Having too old issues open in a repository is not a good idea. Let's go through all of them and make sure they either are not solvable or we solve them somehow.

**Comment by filfreire** [comment]
@yegor256 agreed. BTW, I was also thinking we could do the same for Rultor. This issue, in particular, I believe we can close.

**Comment by yegor256** [comment]
@filfreire OK, closing.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
