### ISSUE TITLE
Errors when installing dependencies on the project

### ISSUE THREAD

**Issue by bjorndonald** [yegor256/tacit#233]
I forked and cloned the project in order to run it on my local device but it keeps producing errors relating to node-sass

There is a simple solution though. We just need to update the grunt-sass to the latest version which is (at the time of writing) 3.1.0.

**Comment by yegor256** [comment]
@bjorndonald I configured GitHub Actions, they work on all three platforms now, see: https://github.com/yegor256/tacit/actions
