### ISSUE TITLE
A converter tool to convert CMS themes to tacit-like classless CSS frameworks

### ISSUE THREAD

**Issue by Immortalin** [yegor256/tacit#25]
Hi, how about a tool to convert CMS themes to tacit-like classless CSS frameworks? CMS e.g. WordPress themes are pretty standard so writing a converter should be quite easy. Furthermore, this would give users more choices and variety when choosing classless CSS frameworks.

**Comment by vkeusebio** [comment]
That doesn't seems to be within the scope. It might be better if you would make it yourself.
