### ISSUE TITLE
Add compiled file to a dist folder

### ISSUE THREAD

**Issue by ylecuyer** [yegor256/tacit#27]
When using tacit with bower it would be usefull to have `tacit.min.css` and `tacit.css` in a dist folder

**Comment by vkeusebio** [comment]
Actually, there is. The reason why `tacit.min.css` is in the root directory is for testing purposes while developing the framework locally in your machine, after every compilation of the SCSS files a `dist` folder will be created containing, for example, `tacit-1.0.0.min.css`.

`tacit.min.css` and `dist/tacit-1.0.0.min.css` are the same but only `tacit.min.css` is used during development and is ignored/removed before pushing changes to your fork.

**Comment by ylecuyer** [comment]
I think you misunderstood the point. What I want to explain is that one
need to compile the scss files to have the resulting css. It is not
possible to start working with tacit by just cloning the repository.

**Comment by vkeusebio** [comment]
Oh, sorry I missed your point. Anyway, now that makes sense.

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by yegor256** [comment]
@jehna no good :( https://github.com/yegor256/tacit/tree/0.5.4

**Comment by jehna** [comment]
@yegor256 ah, the branch was __rultor .. Should've chekout to master before commit.

**Comment by vote539** [comment]
I don't have access to bower/node or any of those fancy command line tools on the server that I have to use (shared host).  I'd really like just a CSS file I can download and drop in.

**Comment by yegor256** [comment]
@vote539 of course, it's here: http://yegor256.github.io/tacit/tacit.min.css

**Comment by henkvantijen** [comment]
Hi Yegor, great stuff. I'd like a NON-minified complete human-editable file ("tacit.css") somewhere. I don't have the ruby/javascript? tools to generate from the sources, but want to tinker a bit with the styles (make smaller font sizes and less space between lines, actually). Editing a minified version is a pita. (I think this is what @vote539 and @ylecuyer asked for too). TIA.

**Comment by filfreire** [comment]
@yegor256, we can close this issue. 

With regards to the user request of
>  It is not possible to start working with tacit by just cloning the repository.

We're already doing this each release, example:
https://github.com/yegor256/tacit/tree/1.2.8/dist

We could follow, for example, Bootstrap's aproach and also place the css results of compilation in a "master"-like branch:
https://github.com/twbs/bootstrap/tree/v4-dev/dist/css

But this violates the idea of the protected master branch discussed in some of your blog posts. And I'd add it would look ugly compared to what we have now, separating development repo and release of artifacts.

**Comment by yegor256** [comment]
@ylecuyer @filfreire that's right, closing

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
