### ISSUE TITLE
Supported browsers & versions?

### ISSUE THREAD

**Issue by cvrebert** [yegor256/tacit#31]
There don't currently seem to be any docs saying which browsers and versions are intended to be supported. Most CSS libraries mention this info; e.g. http://foundation.zurb.com/docs/compatibility.html 
Browser support is an important consideration when choosing between CSS libraries.

**Comment by yegor256** [comment]
@cvrebert make sense, thanks!

**Comment by yegor256** [comment]
@0crat assign @filfreire

**Comment by 0crat** [comment]
> @0crat assign @filfreire  ([here](https://github.com/yegor256/tacit/issues/31#issuecomment-333383875))

@yegor256 Job `gh:yegor256/tacit#31` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @filfreire is not a member of this project yet, but can request to join. @filfreire check your [Zerocracy profile](http://www.0crat.com/u/filfreire) and follow the instructions.

**Comment by filfreire** [comment]
@yegor256 @cvrebert 
added compatibility list through PR https://github.com/yegor256/tacit/pull/95
We also have issues in place to solve browser-specific anomalies.

**Comment by 0crat** [comment]
@filfreire this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/tacit#31`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#31` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by filfreire** [comment]
@yegor256 kindly close this issue. We have the list. We can add more browsers supported to the list later on, with different issues.

**Comment by yegor256** [comment]
@filfreire thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#31` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @filfreire, total is [+420](http://www.0crat.com/u/filfreire).
