### ISSUE TITLE
CSS has validation errors

### ISSUE THREAD

**Issue by cvrebert** [yegor256/tacit#32]
From http://yegor256.github.io/tacit/ :
> By the way, it is compliant with W3C validator requirements: HTML and [CSS](https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fyegor256.github.io%2Ftacit%2F&profile=css3).

Follow the W3C CSS validator link:
![invalid](https://cloud.githubusercontent.com/assets/419884/7874846/3796a4be-056a-11e5-9a75-ce917f5b91a4.png)

**Comment by jehna** [comment]
Quick fix: Remove the paragraph stating it is W3C compilant?

**Comment by vkeusebio** [comment]
Isn't the goal was to keep it W3C compliant?

**Comment by jehna** [comment]
Just a personal opinion that it is not realistic to think the browsers would behave so good nowdays that it'd be even possible to create a good cross-browser css framework that does not have *any* browser hacks.

For reference, the popular bootstrap framework had [37 errors](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fmaxcdn.bootstrapcdn.com%2Fbootstrap%2F3.3.4%2Fcss%2Fbootstrap.min.css&profile=css3&usermedium=all&warning=1&vextwarning=true&lang=en) that, at least with a quick glance, were all related to specific browser overrides.

**Comment by yegor256** [comment]
@cvrebert thanks for reporting. The goal is to keep it 100% W3C compliant. The problem is that this check is not yet part of our deployment pipeline. I'll try to automate it.

**Comment by jehna** [comment]
The current error is the firefox responsive hack, could either fix the firefox browser or look for some other workaround for it

**Comment by yegor256** [comment]
@jehna or maybe we can inform W3C validator about it somehow... to suppress its error reporting. If not, would be great to find some workaround, as you suggest

**Comment by jehna** [comment]
@yegor256 tried the "Vendor Extensions as Warnings" flag but still got the errors :/
