### ISSUE TITLE
<pre><code> nesting  formatting style suggestion

### ISSUE THREAD

**Issue by alexjj** [yegor256/tacit#48]
The HTML5 docs for [pre](https://www.w3.org/TR/html5/grouping-content.html#the-pre-element) and [code](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-code-element.html) state that when you want block code to not wrap to use `<pre><code> foo </code></pre>`.

However, tacit css (in my opinion) doesn't then format this as expected. If I use `<pre><code>`it's rendered just as pre and (seems to) ignore code but if I use `<code><pre>`it looks better with the darker background - although perhaps the margin is a bit large.

When converting from markdown (and possibly other formats - I've not tested) the conversion does `<pre><code>`. 

[Example](http://scratchpad.io/deafening-tongue-7720).

**Comment by yegor256** [comment]
@alexjj thanks for the ticket. can you submit a pull request please?

**Comment by alexjj** [comment]
I ended up just deleting everything the code block under pre, but now I'm not sure I like that either! hmm... :confused:

**Comment by yegor256** [comment]
@alexjj what's up with this? Do we still need some changes?

**Comment by alexjj** [comment]
I ended up rolling my own CSS, as I only needed a few features. I'd say just keep as is unless you or another wants to change it.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#48` was not in scope
