### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by debarshri** [yegor256/tacit#49]
I am wondering is there is easyway I can make clean navbars,

something like 

|title| nav1 | nav2 |

Couldnt find a stackoverflow page, so I am asking it here.

**Comment by yegor256** [comment]
@debarshri try this (as it's done at the bottom of ):

```
<nav>
  <ul>
    <li>one</li>
    <li>two</li>
    <li>three</li>
  </ul>
</nav>
```

**Comment by debarshri** [comment]
This is so cool. I like it.
