### ISSUE TITLE
Sticky footer

### ISSUE THREAD

**Issue by debarshri** [yegor256/tacit#50]
Hey Yegor. Sorry spam your issue list.

Do you know if I can make sticky footer. Or footer thats at the bottom of the page.

right now the footer looks a bit weird, I think.

**Comment by yegor256** [comment]
@debarshri no, it's not possible with pure HTML5 now. you have to use styles/classes for that. or I'm wrong about HTML5? does it have that tags?

**Comment by debarshri** [comment]
Im talking about this tag
http://www.w3schools.com/tags/tag_footer.asp

**Comment by yegor256** [comment]
@debarshri I see what you need, but I believe that sticking anything to the page is against the philosophy of HTML. an HTML is a document that you can scroll, up and down. nothing should be sticking to the device/screen. see my point?

**Comment by debarshri** [comment]
May be the footer is always in the end of the page. Not screen. How about
that?

**Comment by yegor256** [comment]
@debarshri it is at the end of the page, if you put it there... or I didn't understand you?

**Comment by konsumer** [comment]
Put [this](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/) in your css.

**Comment by akshayvinchurkar1** [comment]
@konsumer good point

**Comment by filfreire** [comment]
Let's close this issue following up @yegor256's comment:
https://github.com/yegor256/tacit/issues/50#issuecomment-185988543

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#50` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
