### ISSUE TITLE
select looks 'lifted'

### ISSUE THREAD

**Issue by sobolevn** [yegor256/tacit#60]
Here's what we have now:
<img width="169" alt="2017-03-31 17 46 06" src="https://cloud.githubusercontent.com/assets/4660275/24555477/00f00058-163a-11e7-8a5f-ffd71e4ea9a3.png">

I guess, it should be like that:

```css
select {
    margin-bottom: 0;
}
```

<img width="184" alt="2017-03-31 17 47 19" src="https://cloud.githubusercontent.com/assets/4660275/24555503/1cb7981e-163a-11e7-9969-e686e450380e.png">

I will send a PR in a few hours.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@sobolevn which browser are you using?

**Comment by sobolevn** [comment]
Latest Chrome.

**Comment by yegor256** [comment]
@sobolevn can you please give a piece of your HTML? I will try to reproduce the problem and fix it. Thanks.

**Comment by sobolevn** [comment]
```html
<p><label for="id_extra">Extra:</label> <select multiple="multiple" id="id_extra" name="extra">
<option value="1">Cheese</option>
<option value="2">Ham</option>
<option value="3">Olives</option>
<option value="4">Tomato</option>
<option value="5">Onion</option>
<option value="6">Bacon</option>
<option value="7">Chicken</option>
<option value="8">Pineapples</option>
</select></p>
```

Here's a fiddle: https://jsfiddle.net/zdqw0bpj/

Sorry for the bad issue report in the first place.

**Comment by yegor256** [comment]
@sobolevn I wasn't able to reproduce the problem in 5d4da21 Can you please provide full HTML, with `head`?

**Comment by sobolevn** [comment]
Is the fiddle good enough? https://jsfiddle.net/zdqw0bpj/

For me it looks like that:
<img width="765" alt="2017-04-19 11 40 09" src="https://cloud.githubusercontent.com/assets/4660275/25170967/f92001ec-24f4-11e7-81b9-ca7ef15a24ab.png">

**Comment by yegor256** [comment]
@sobolevn I don't see `tacit.css` there

**Comment by sobolevn** [comment]
It is in "External Resources".
<img width="247" alt="2017-04-19 13 13 08" src="https://cloud.githubusercontent.com/assets/4660275/25175065/05597e40-2502-11e7-9a98-abef7de16061.png">

**Comment by yegor256** [comment]
@sobolevn please, send a pull request. Thanks!

**Comment by filfreire** [comment]
@sobolevn, @yegor256 PR #98 was merged and closes this issue, could you kindly close it?

**Comment by filfreire** [comment]
@sobolevn thanks for reporting this issue and #72 👍

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#60`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#60` is not in scope.
