### ISSUE TITLE
Upload tacit to NPM

### ISSUE THREAD

**Issue by jmaister** [yegor256/tacit#67]

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.9`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.0`

**Comment by yegor256** [comment]
@jmaister it seems to be there: https://www.npmjs.com/package/tacit-css

**Comment by yegor256** [comment]
@jmaister please, close this ticket if you like the result

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#67` was not in scope
