### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#73]
Add a CONTRIBUTING.md file with contribution guidelines to tacit project.

**Comment by yegor256** [comment]
@filfreire do we really need this? We already have https://github.com/yegor256/tacit#how-to-contribute section.

**Comment by filfreire** [comment]
@yegor256 the separate file is a Github guideline https://github.com/blog/1184-contributing-guidelines  (view the image there).

I'd suggest following it because if we do, we get this:

> Then we (Github) will add a link to your (CONTRIBUTING) file when a contributor creates an Issue or opens a Pull Request.

**Comment by yegor256** [comment]
@filfreire hm, I didn't know about this. Of course, let's do it.

**Comment by filfreire** [comment]
@yegor256 we can close this issue after merging PR https://github.com/yegor256/tacit/pull/90 please follow-up

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#73` was not in scope
