### ISSUE TITLE
Firefox specific issues

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#78]
WIP - To be defined.

**Comment by tofran** [comment]
Firefox does not break text after input's
![20171024_selection_01](https://user-images.githubusercontent.com/5692603/31917266-732d02e0-b84e-11e7-8dd8-99409c3e1031.png)

**Comment by teriyakigod2** [comment]
I don't think it's a FF issue, because in the current `index.html` version "Your age" is just a plain text, so it can't be considered as a flexbox item.

**Comment by filfreire** [comment]
@teriyakigod2, true, notice the difference then between Chrome and FF:

<img width="1920" alt="chrome" src="https://user-images.githubusercontent.com/11976836/51944678-f3d4bb00-241c-11e9-8cb9-96c5cabfe958.png">
<img width="1920" alt="firefox" src="https://user-images.githubusercontent.com/11976836/51944679-f3d4bb00-241c-11e9-91ae-452f8ee46f1e.png">


I suggest we need to apply some fix on the index.html, maybe replacing the plain text and putting it on a proper element.

**Comment by 0crat** [comment]
Job [#78](https://github.com/yegor256/tacit/issues/78) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#78](https://github.com/yegor256/tacit/issues/78) assigned to @filfreire[/z](https://www.0crat.com/u/filfreire), here is [why](https://www.0crat.com/footprint/C7BNDNSNR/784b068a-6b9c-44ac-b2ab-76dd7469a32d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @filfreire[/z](https://www.0crat.com/u/filfreire)

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by filfreire** [comment]
Closing this issue.  `<label>` element problem fixed with pr #184

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#78](https://github.com/yegor256/tacit/issues/78); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#78](https://github.com/yegor256/tacit/issues/78) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @filfreire[/z](https://www.0crat.com/u/filfreire)
