### ISSUE TITLE
Fix link between tacit and 0crat

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#85]
On some projects after creating an issue, 0crat creates an automatic comment:

> @yegor256 please, pay attention to this issue

This isn't happening for tacit

**Comment by filfreire** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire this is because you are the ARC (architect) in Tacit and when you create tickets, 0crat doesn't notify you. The default idea is to notify project ARC about all new incoming tickets. I will create a test one and you will see what will happen. See: #86

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#85` was not in scope
