### ISSUE TITLE
License into README

### ISSUE THREAD

**Issue by yegor256** [yegor256/tacit#86]
Let's add license to the end of README, like it's done here, for example: https://github.com/yegor256/cactoos#license-mit

**Comment by 0crat** [comment]
@filfreire please, pay attention to this issue

**Comment by filfreire** [comment]
@yegor256 implementation done in PR https://github.com/yegor256/tacit/pull/87

**Comment by filfreire** [comment]
@yegor256 we can close this one. Development is done.

**Comment by yegor256** [comment]
@filfreire thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#86` was not in scope
