### ISSUE TITLE
Create a Logo for Tacit

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#88]
We need a logo for Tacit, similar to other recent projects like

Cactoos - https://github.com/yegor256/cactoos/blob/master/README.md
ReHTTP - https://github.com/yegor256/rehttp
ThreeCopies - https://github.com/yegor256/threecopies

**Comment by yegor256** [comment]
@filfreire totally agree, let's pick one from flaticon: https://www.flaticon.com/ ?

**Comment by filfreire** [comment]
@yegor256 what do you think of these:
https://www.flaticon.com/free-icon/strawberry_579047
https://www.flaticon.com/free-icon/crayon_579603
https://www.flaticon.com/free-icon/vice_579615
https://www.flaticon.com/free-icon/brush_579602

**Comment by yegor256** [comment]
@filfreire I like the strawberry)

**Comment by akshayvinchurkar1** [comment]
I can create one if you guys like I am designer + front-end developer
give me some ideas tacit is framework without classes right then we can try Pacman face and a dot after then it looks like we eat class .  hows that?

**Comment by akshayvinchurkar1** [comment]
![tacit](https://user-images.githubusercontent.com/29745555/31225204-9ab13a7a-a9ee-11e7-9e6b-8180e63f63e8.jpg)

**Comment by filfreire** [comment]
@yegor256 what do you think?

**Comment by yegor256** [comment]
@filfreire @akshayvinchurkar1 I like the concept (we are eating the dot), but I don't like the implementation. Can you try again? I don't think we need a text in the logo.

**Comment by akshayvinchurkar1** [comment]
@yegor256  @filfreire what you think about this
![tacit](https://user-images.githubusercontent.com/29745555/31528718-b86dddfc-aff2-11e7-91f0-e549c8641ff2.jpg)

**Comment by yegor256** [comment]
@akshayvinchurkar1 @filfreire much better! Can we rotate it as it was before, remote the dot, leave only the dash sign, and remove the waves and the gradient. It will be just the yellow circle and the dash. Should be nice)

**Comment by akshayvinchurkar1** [comment]
@yegor256 ok

**Comment by akshayvinchurkar1** [comment]
![tacit](https://user-images.githubusercontent.com/29745555/31544567-0db49cec-b039-11e7-9a08-c59cf48e5819.png)

**Comment by filfreire** [comment]
@akshayvinchurkar1 seems nice 👍 
@yegor256 what do you think?

**Comment by yegor256** [comment]
@filfreire @akshayvinchurkar1 like!)

**Comment by akshayvinchurkar** [comment]
Ok then lets use it

**Comment by filfreire** [comment]
@akshayvinchurkar really nice work 👍 
Can you provide an SVG file.

**Comment by akshayvinchurkar** [comment]
@filfreire oh thank you mate sure 😊

**Comment by akshayvinchurkar1** [comment]
[tacit logo.zip](https://github.com/yegor256/tacit/files/1386143/tacit.logo.zip)

GitHub is not supporting SVG file to upload I need to wrap into zip file

**Comment by akshayvinchurkar1** [comment]
@filfreire @yegor256 what is the status of this PR?

**Comment by filfreire** [comment]
@akshayvinchurkar1 @akshayvinchurkar I'll submit a PR today with the logo.
@yegor256 FYI

**Comment by filfreire** [comment]
@yegor256 closing this issue.

@akshayvinchurkar / @akshayvinchurkar1 thank you for the contribution 👍

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#88`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#88` is not in scope.
