### ISSUE TITLE
Convert table to list if the screen is to narrow

### ISSUE THREAD

**Issue by yegor256** [yegor256/tacit#89]
When the table is too wide and the screen is too small it would be better to turn it into a list, I believe. Otherwise, it's not readable. We can just turn `display` from `table-cell` to `block` for all `td` and hide the `thead`. Something like that.

**Comment by 0crat** [comment]
@filfreire please, pay attention to this issue

**Comment by filfreire** [comment]
@teriyakigod2 let's divide this into 2 smaller issues.
1 - When the screen is small (mobile screen) - we follow the approach we can see http://www.zold.io/health.html -> we'll do this in the context of this ticket (#89)

2- When the screen is not necessarily small, but the table overflows the main `<section>` element (like on 0crat's board page), let's do it in another issue (#182)

**Comment by filfreire** [comment]
Closing this issue, implemented in PR #189

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#89` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
