### ISSUE TITLE
Gender Selection Issue 

### ISSUE THREAD

**Issue by Kyokou** [yegor256/tacit#9]
Change the default selection of gender to "Won't Tell". It's sexist to have "male" be the default and expected option. 

Bonus feminist points if you put Female above Male as the 2nd Option. 
Bonus LGBTQRSTUV points if you include "Neither", "Both", and "Other" options.

**Comment by yegor256** [comment]
@Kyokou thanks for the comment, see d965826

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.2`

**Comment by Kyokou** [comment]
I made this mostly in jest since you're from San Francisco. But applause nonetheless for treating it as a serious issue. :+1: 

Closed.

**Comment by yegor256** [comment]
we take these things seriously... in San Francisco :)

**Comment by Kyokou** [comment]
Well you missed out on the bonus LGBTQRSTUV  points! 

You'd be surprised at the number of people who will complain that they are genderfluid and identify themselves as both female and male depending on their mood or the day. 

Gender politics aside - I like this repo. Clever idea and it looks to be coming together nicely.

**Comment by yegor256** [comment]
@Kyokou thanks for using it :) maybe we should replace this entire dropdown box with something more neutral... any ideas?

**Comment by Kyokou** [comment]
Cats or Dogs:
Select One
Cats
Dogs

**Comment by yegor256** [comment]
@Kyokou I like the selection, but what is the question? "Your favorite pet"?

**Comment by Kyokou** [comment]
"Cats or Dogs?" 

Favorite pet would mean people who like hamsters, snakes, birds, ferrets, gerbils, frogs, lizards, and a variety of other animals would feel left out. Their favorite pet isn't on the list! 

"Cats or Dogs?" is merely asking an opinion between two arbitrary choices.

**Comment by yegor256** [comment]
@Kyokou well, I'm trying to keep this "form" as realistic as possible. It should look like a form for subscription. Would be strange to have such a question on a website subscription page: cats or dogs? :) It should be something more realistic..

**Comment by Kyokou** [comment]
Fair point. How about a niche that also lets you showcase other input types? I like icecream. 

What day is the best day to have icecream? 
[input form type="date"] 

What is your favorite flavor of Neapolitan ice cream?
[Select Your Favorite]
[Chocolate]
[Strawberry] 
[Vanilla]

How many servings of icecream do you have per week, on average?
[input form type="num"] 

Do you consider yourself an icecream enthusiast/addict? 
[Radio] Yes [Radio] No

[checkbox] Can we contact you with special offers on icecream?

**Comment by yegor256** [comment]
@Kyokou good point about radio button, see https://github.com/yegor256/tacit/issues/16

I like the icecream selector, will do it soon

**Comment by makoru-hikage** [comment]
Disgusting
