### ISSUE TITLE
validate CSS against W3C validator

### ISSUE THREAD

**Issue by yegor256** [yegor256/tacit#91]
Would be great to validate our CSS through Jigsaw CSS validator: https://jigsaw.w3.org/css-validator/

And we should do that in an automated way, during the build.

BTW, now it's clean: https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fcdn.rawgit.com%2Fyegor256%2Ftacit%2Fgh-pages%2Ftacit-css.min.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

Maybe we can also add that nice buttons (validated by W3C) to the bottom of our index page.

**Comment by 0crat** [comment]
@filfreire please, pay attention to this issue

**Comment by akshayvinchurkar1** [comment]
issue is still open close it now @yegor256 @filfreire

**Comment by filfreire** [comment]
@akshayvinchurkar1 we're still missing the part of doing the validation automatically in the build

**Comment by filfreire** [comment]
@rultor release, tag is `1.4.0`

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#91` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
