### ISSUE TITLE
Fix tacit CDN link in index.html

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#97]
Currently on index.html file, tacit points to a specific version, example:
```
    <link rel="stylesheet" href="https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-1.1.1.min.css"/>
```

The problem is the actual file can only be found currently through this link:
https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css.min.css

**Comment by filfreire** [comment]
@akshayvinchurkar1 my mistake, the actual file (with version) can be found with
```
https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-VERSION.min.css
```
Currently it's
```
https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-VERSION.min.css
```

can you make the change on PR https://github.com/yegor256/tacit/pull/98 ?

**Comment by akshayvinchurkar1** [comment]
@filfreire sure mate

**Comment by filfreire** [comment]
@akshayvinchurkar1 
all of the following work fine
* `https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.1.1.min.css`
* `https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css.min.css`
* `https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit.min.css`

The one with version `https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.1.1.min.css` is generated automatically on release.

So there's 3 ways of solving the issue. If we leave it as
`https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-VERSION.min.css` it'll be ok after release.

**Comment by akshayvinchurkar1** [comment]
@filfreire ok mate then closed the issue

**Comment by filfreire** [comment]
PR #98 closes this issue.

**Comment by filfreire** [comment]
@akshayvinchurkar1 thank you!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#97`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#97` is not in scope.
